### ISSUE TITLE
Link to prometheus arduino library used in this project

### ISSUE THREAD

**Issue by croisez** [z2amiller/sensorboard#3]
Hi, could you document the link to the prometheus Arduino library used in this project?

**Comment by z2amiller** [comment]
Added a link to the README.md.  (https://github.com/z2amiller/sensorboard/commit/1cc4190ea89385d12b81b523408ae3b3c466286c)   The required libraries are in my libraries repo (https://github.com/z2amiller/libraries).  Thanks for filing an issue and let me know if you need any other help setting it up.
